### ISSUE TITLE
fluffyscratch no work

### ISSUE THREAD

**Issue by FunctionalMetatable** [JeffaloBob/notifier#3]
fluffyscratch's message count api doesnt work anymore because the user agent problem.

i gave a fix (see https://github.com/hamptonmoore/FluffyScratch/pull/13) but it hasnt been deployed yet. you should make your own vercel serverless function for this
proof: https://api.scratch.mit.edu/users/griffpatch/messages/count vs https://fluffyscratch.hampton.pw/notifications/v2/griffpatch

**Comment by jeffalo** [comment]
my notifier is no longer maintained, please use an alternative like the one in Scratch Addons.
